export const preferenceLabels = {
  citrus: "시트러스",
  sweet: "달달",
  woody: "우디",
  floral: "플로럴",
  aqua: "아쿠아",
  cozy: "포근한",
  cool: "차가운",
  calm: "차분한",
  oriental: "오리엔탈",
  gourmand: "구르망",
  powder: "파우더리",
  fruity: "프루티",
  musk: "머스크",
  green: "그린",
  herbal: "허벌",
};

export const perfumeList = [
  {
    id: "citrus-dawn",
    name: "Citrus Dawn",
    brand: "Sunrise Atelier",
    description: "햇살이 부드럽게 감싸는 아침, 산뜻한 감귤 향으로 기분을 깨워주는 시트러스 향수입니다.",
    tags: ["citrus", "aqua"],
    accords: ["산뜻함", "청량감"],
    primary_tag: "citrus",
    seasonality: ["spring", "summer"],
    weather: ["sunny", "humid"],
    notes: {
      top: ["베르가못", "자몽", "유자"],
      middle: ["그린티", "오렌지 블러섬"],
      base: ["머스크", "시더우드"],
    },
  },
  {
    id: "floral-mist",
    name: "Floral Mist",
    brand: "Bloom House",
    description: "봄날 정원에서 느껴지는 꽃내음. 은은한 플로럴 향이 따뜻하게 스며듭니다.",
    tags: ["floral"],
    accords: ["부드러움", "우아함"],
    primary_tag: "floral",
    seasonality: ["spring"],
    weather: ["sunny", "humid"],
    notes: {
      top: ["레몬 블러섬", "라일락"],
      middle: ["자스민", "피오니"],
      base: ["화이트 머스크", "샌달우드"],
    },
  },
  {
    id: "woodland-trail",
    name: "Woodland Trail",
    brand: "Forest Echo",
    description: "촉촉한 숲속을 거니는 듯한 우디 향으로 안정감과 깊이를 전해줍니다.",
    tags: ["woody"],
    accords: ["깊이감", "안정감"],
    primary_tag: "woody",
    seasonality: ["autumn", "winter"],
    weather: ["cloudy", "rainy"],
    notes: {
      top: ["핑크 페퍼", "세이지"],
      middle: ["시더우드", "베티버"],
      base: ["앰버", "파출리"],
    },
  },
  {
    id: "honey-blossom",
    name: "Honey Blossom",
    brand: "Nectar Studio",
    description: "달콤한 벌꿀과 꽃향기가 어우러져 포근한 감성을 담은 향수입니다.",
    tags: ["sweet", "floral"],
    accords: ["포근함", "달콤함"],
    primary_tag: "sweet",
    seasonality: ["autumn"],
    weather: ["cloudy"],
    notes: {
      top: ["허니", "페어"],
      middle: ["티아레 플라워", "오키드"],
      base: ["바닐라", "캐셔머란"],
    },
  },
  {
    id: "marine-whisper",
    name: "Marine Whisper",
    brand: "Azure Lab",
    description: "맑은 바다 바람이 스치는 듯한 아쿠아 향이 청량하게 펼쳐집니다.",
    tags: ["aqua", "citrus"],
    accords: ["청량감", "자유로움"],
    primary_tag: "aqua",
    seasonality: ["summer"],
    weather: ["humid", "windy"],
    notes: {
      top: ["라임", "바질"],
      middle: ["시솔트", "드리프트우드"],
      base: ["앰버그리스", "화이트 머스크"],
    },
  },
  {
    id: "amber-velvet",
    name: "Amber Velvet",
    brand: "Nocturne Atelier",
    description: "깊고 따뜻한 앰버와 우디 노트가 어우러져 고혹적인 분위기를 완성합니다.",
    tags: ["woody", "sweet"],
    accords: ["관능미", "따뜻함"],
    primary_tag: "woody",
    seasonality: ["autumn", "winter"],
    weather: ["night"],
    notes: {
      top: ["베르가못", "사프란"],
      middle: ["장미", "앰브록산"],
      base: ["앰버", "통카빈"],
    },
  },
  {
    id: "candy-cloud",
    name: "Candy Cloud",
    brand: "Pastel Mood",
    description: "솜사탕처럼 달콤하고 가벼운 노트가 기분 좋은 설렘을 전합니다.",
    tags: ["sweet"],
    accords: ["달콤함", "경쾌함"],
    primary_tag: "sweet",
    seasonality: ["winter"],
    weather: ["snowy", "night"],
    notes: {
      top: ["라즈베리", "핑크 페퍼"],
      middle: ["코튼 플라워", "프리지아"],
      base: ["머스크", "바닐라"],
    },
  },
  {
    id: "sage-rain",
    name: "Sage Rain",
    brand: "Cloudline",
    description: "비 온 뒤 젖은 공기와 허브가 전하는 차분한 아쿠아 향입니다.",
    tags: ["aqua", "woody"],
    accords: ["차분함", "맑음"],
    primary_tag: "aqua",
    seasonality: ["spring", "summer"],
    weather: ["rainy"],
    notes: {
      top: ["만다린", "레인 어코드"],
      middle: ["세이지", "아이리스"],
      base: ["오크모스", "시더"],
    },
  },
  {
    id: "amber-night",
    name: "Amber Night",
    brand: "Nocturne",
    description: "짜릿한 앰버와 스파이스가 어우러진 야상곡 같은 향.",
    tags: ["woody", "oriental"],
    accords: ["깊이감", "관능미"],
    primary_tag: "woody",
    seasonality: ["autumn", "winter"],
    weather: ["night"],
    notes: {
      top: ["클로브", "핑크 페퍼"],
      middle: ["앰버", "실크 우드"],
      base: ["바닐라", "머스크"],
    },
  },
  {
    id: "blooming-tea",
    name: "Blooming Tea",
    brand: "Teaflor",
    description: "따뜻한 찻잔 위로 잔잔히 피어오르는 꽃향기와 시트러스가 어우러집니다.",
    tags: ["floral", "citrus"],
    accords: ["부드러움", "상큼함"],
    primary_tag: "floral",
    seasonality: ["spring", "summer"],
    weather: ["sunny"],
    notes: {
      top: ["유자", "라임"],
      middle: ["화이트 티", "카모마일"],
      base: ["머스크", "아이리스"],
    },
  },
  {
    id: "coffee-bloom",
    name: "Coffee Bloom",
    brand: "Roastery",
    description: "막 내린 커피의 구수함과 포근한 우디 노트가 어우러진 향.",
    tags: ["cozy", "sweet"],
    accords: ["포근함", "구수함"],
    primary_tag: "cozy",
    seasonality: ["autumn", "winter"],
    weather: ["cloudy", "night"],
    notes: {
      top: ["아몬드", "카카오"],
      middle: ["로스티드 커피", "통카빈"],
      base: ["시더", "앰버"],
    },
  },
  {
    id: "evening-fig",
    name: "Evening Fig",
    brand: "Maison Feeg",
    description: "황혼 무렵 무화과 나무 아래 퍼지는 달콤한 과실 향.",
    tags: ["sweet", "woody"],
    accords: ["달콤함", "그린"],
    primary_tag: "sweet",
    seasonality: ["summer", "autumn"],
    weather: ["sunny", "night"],
    notes: {
      top: ["자몽", "무화과 잎"],
      middle: ["자스민", "아이리스"],
      base: ["파출리", "샌달우드"],
    },
  },
  {
    id: "cotton-haze",
    name: "Cotton Haze",
    brand: "Soft Co.",
    description: "햇살이 스며든 코튼 시트처럼 가볍고 포근한 파우더리 향.",
    tags: ["powder", "calm"],
    accords: ["포근함", "차분함"],
    primary_tag: "powder",
    seasonality: ["spring", "autumn"],
    weather: ["cloudy"],
    notes: {
      top: ["알데하이드", "베르가못"],
      middle: ["코튼 플라워", "아이리스"],
      base: ["머스크", "캐시미어 우드"],
    },
  },
];

export const dummyWeather = {
  location: "서울",
  temperature: 23,
  description: "구름 사이로 비치는 따뜻한 햇살",
  humidity: 52,
  status: "sunny",
  fetchedAt: new Date().toISOString(),
};

export const dummyUser = {
  name: "게스트",
};
